/**
 * capture_flows.mjs — regenerate the Category-4 flow definitions from the running app.
 *
 * WHY THIS EXISTS. The Part-1 audit traced its five Category-4 flows "from a real
 * browser session" and committed only one of them (flows/mainpage.urls). The other
 * four existed solely as a number in AUDIT_REPORT.md, so nobody — including the
 * author — could re-measure them. docs/week6-perf-regression.md §8 recorded that as
 * "a reproducibility gap in the committed harness". This script closes it: the flow
 * definitions are now generated by an instrument instead of transcribed by hand.
 *
 * WHAT IT DOES. For each flow it opens a FRESH browser context — which matters, and
 * is the whole reason this is a script rather than a devtools session. A soft reload
 * reuses the HTTP cache and TanStack Query's in-memory cache, and both silently
 * suppress calls: an observed /issues reload fired 4 requests where a genuinely cold
 * load fires 10. A cold context is the only way the captured set is the real one.
 *
 * Auth uses the same path as run_flow.sh (POST /api/auth/login with the dev fixture,
 * then the session cookie), so the two instruments authenticate identically.
 *
 * USAGE — prefer the wrapper, which resolves the document ids from the database:
 *   bash bench/cat4-queries/run_capture.sh
 *
 * SEED-SPECIFIC OUTPUT. The `document` and `weekboard` flows address a document by
 * UUID, so their .urls files only work against the seed they were captured from.
 * After a re-seed the baked ids 404, and a flow of 404s still produces a number —
 * plausible, reproducible, and wrong. Re-run the capture after any re-seed, and
 * check run_flow.sh's per-URL echo for non-200s before believing a count.
 *
 * Writes flows/<name>.urls. Review the diff before committing — a changed call set
 * is a real change in the app, not noise, and the delta is worth reading.
 */
import { chromium } from '@playwright/test';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const FLOWS = join(HERE, 'flows');

const WEB = process.env.WEB ?? 'http://localhost:5173';
const API = process.env.API ?? 'http://localhost:3000';
const EMAIL = process.env.SHIP_EMAIL ?? 'dev@ship.local';
const PASSWORD = process.env.SHIP_PASSWORD ?? 'admin123';

/**
 * Settle time after load. The app's providers fire in a burst; `networkidle` alone
 * returns before late effects (agent findings, standup status) have issued.
 */
const SETTLE_MS = Number(process.env.SETTLE_MS ?? 2500);

/**
 * Document ids are read from the database rather than hardcoded, so the script
 * survives a re-seed. Pass DOC_ID / SPRINT_ID to pin specific ones.
 */
const DOC_ID = process.env.DOC_ID;
const SPRINT_ID = process.env.SPRINT_ID;

const flows = [
  {
    name: 'mainpage',
    route: '/my-week',
    title: 'Cold authenticated load of the main page (/my-week)',
  },
  {
    name: 'document',
    route: () => `/documents/${DOC_ID}`,
    title: 'Cold authenticated load of a single wiki document (/documents/:id)',
  },
  {
    name: 'issues',
    route: '/issues',
    title: 'Cold authenticated load of the issues list (/issues)',
  },
  {
    name: 'weekboard',
    route: () => `/documents/${SPRINT_ID}/issues`,
    title: 'Cold authenticated load of the week board (sprint document, Issues tab)',
  },
  {
    name: 'search',
    route: '/my-week',
    title: 'Search: command palette open + an @-mention query',
    // The Cmd-K palette filters client-side over the documents already loaded, so
    // the only server cost of search is the mention endpoint. Driving the editor UI
    // to produce it is brittle; issuing the request the editor issues is not, and it
    // is the same route with the same handler.
    // ONE mention query, deliberately. The Part-1 baseline defines this flow as
    // "Cmd-K + @-mention" -- singular -- and scores it at 9 queries. Firing one
    // request per keystroke would measure a flow the baseline never measured and
    // inflate the delta by ~4 queries per extra keystroke.
    async after(page) {
      await page.keyboard.press('ControlOrMeta+k');
      await page.waitForTimeout(400);
      await page.evaluate(() =>
        fetch('/api/search/mentions?q=rev', { credentials: 'include' })
      );
    },
  },
];

async function login(request) {
  // Assert we are talking to Ship before trusting anything downstream. Another
  // project's dev server on :3000 answers 200 with HTML, and the failure that
  // produces ("Unexpected token '<'") points at JSON parsing rather than at the
  // real cause, which is that the API is not the one you meant.
  const probe = await request.get(`${API}/api/csrf-token`);
  const body = await probe.text();
  if (!probe.ok() || !body.trimStart().startsWith('{')) {
    throw new Error(
      `${API}/api/csrf-token returned ${probe.status()} and did not look like JSON.\n` +
      `Is the Ship API running there? Set API=http://localhost:<port> (or API_PORT=<port>).\n` +
      `First bytes: ${body.slice(0, 80)}`
    );
  }
  const csrf = JSON.parse(body);
  const res = await request.post(`${API}/api/auth/login`, {
    headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf.token },
    data: { email: EMAIL, password: PASSWORD },
  });
  if (!res.ok()) throw new Error(`login failed: ${res.status()}`);
  const cookie = (await request.storageState()).cookies.find((c) => c.name === 'session_id');
  if (!cookie) throw new Error('login succeeded but no session_id cookie was set');
  return cookie.value;
}

const main = async () => {
  if (!DOC_ID || !SPRINT_ID) {
    throw new Error('DOC_ID and SPRINT_ID must be set — run `bash bench/cat4-queries/run_capture.sh`, which resolves both from the database');
  }
  mkdirSync(FLOWS, { recursive: true });
  const browser = await chromium.launch();

  const authCtx = await browser.newContext({ baseURL: API });
  const sessionId = await login(authCtx.request);
  await authCtx.close();

  const stamp = new Date().toISOString().slice(0, 10);

  for (const flow of flows) {
    // Fresh context per flow: empty HTTP cache, empty query cache, cold load.
    const ctx = await browser.newContext({ baseURL: WEB });
    await ctx.addCookies([
      { name: 'session_id', value: sessionId, url: WEB, sameSite: 'Lax' },
    ]);
    const page = await ctx.newPage();

    const seen = [];
    page.on('request', (req) => {
      if (req.method() !== 'GET') return;
      const u = new URL(req.url());
      if (!u.pathname.startsWith('/api/')) return;
      seen.push(u.pathname + u.search);
    });

    const route = typeof flow.route === 'function' ? flow.route() : flow.route;
    await page.goto(route, { waitUntil: 'networkidle' });
    await page.waitForTimeout(SETTLE_MS);
    if (flow.after) {
      await flow.after(page);
      await page.waitForTimeout(SETTLE_MS);
    }

    const header = [
      `# ${flow.title}.`,
      `# Captured ${stamp} by bench/cat4-queries/capture_flows.mjs against a FRESH`,
      `# browser context (cold HTTP + query cache), route ${route}.`,
      `# Replayed by run_flow.sh for exact query counting. Regenerate, do not hand-edit.`,
    ].join('\n');

    const body = seen.join('\n');
    writeFileSync(join(FLOWS, `${flow.name}.urls`), `${header}\n${body}\n`, 'utf8');
    console.log(`${flow.name.padEnd(10)} ${String(seen.length).padStart(2)} GET /api calls  ->  flows/${flow.name}.urls`);
    for (const u of seen) console.log(`             ${u}`);

    await ctx.close();
  }

  await browser.close();
};

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
